apiVersion: v1
kind: Pod
metadata:
  name: master
  namespace: slurm-cluster
  labels:
    app: master
spec:
  containers:
  - name: master
    image: sinonkt/docker-slurmctld
    ports:
    - name: ssh-port
      containerPort: 22
      protocol: TCP
    - name: slurmctld-port
      containerPort: 6817
      protocol: TCP
    envFrom:
      - configMapRef:
          name: default-envs
    securityContext:
      capabilities:
        add: ["SYS_ADMIN"]
    volumeMounts:
    - name: cgroup
      mountPath: /sys/fs/cgroup
      readOnly: true
    - name: etc-slurm
      mountPath: /etc/slurm
      readOnly: true
  volumes:
  - name: cgroup
    hostPath:
      path: /sys/fs/cgroup
      type: Directory
  - name: etc-slurm
    hostPath:
      path: /Users/Krittin/Code/sinonkt/slurm-on-kubernetes/etc/slurm
      type: Directory