apiVersion: v1
kind: PersistentVolume
metadata:
  name: share-nfs
  namespace: slurm-cluster
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  claimRef:
    namespace: slurm-cluster
    name: share-nfs
  nfs:
    path: /home
    server: nfs.slurm-cluster.svc.cluster.local