apiVersion: v1
kind: Service
metadata:
  name: slurmd
  namespace: slurm-cluster
  labels:
    app: compute
spec:
  ports:
  - name: slurmd
    port: 6818
  clusterIP: None
  selector:
    app: compute